# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'CloudNotes'do
      pod 'SwiftyDropbox'
  # Pods for CloudNotes

  target 'CloudNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudNotesUITests' do
    # Pods for testing
  end

end
